
# dataset info
#dataset_name: "EUVP" 
#dataset_path: "/home/hassan/Documents/GitHub/FUnIE-GAN/PyTorch/samples/FunieGAN/EUVP/Paired"


dataset_name: "UIEB" 
dataset_path: "/home/hassan/Documents/GitHub/FUnIE-GAN/PyTorch/samples/FunieGAN/UIEB"

# image info
chans: 3
im_width: 256
im_height: 256

# other params
val_interval: 10 # steps
ckpt_interval: 20  # epochs



 
